### ISSUE TITLE
Website: Cookie Consent, Privacy Policy, Terms etc.

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#16]
# TODO

- Consent Manager => For GDPR
  - ~~use service? e.g. cookiebot~~ => costs $10+
  - implement ourselves:
    - [ ] ask for consent (UI), maybe use klaro?
       - List Purpose, Data processor (Name, Country, Privacy Policy)
       - Default to only necessary (opt-in)
       - No nudging/dark patterns
    - [ ] allow to revoke consent/edit choices (linked in footer and/or privacy policy page)
    - [ ] save consent ids
    - [ ] delay embeds (iframe/script)
    - [ ] allow per-use consent at the place of embedding if global consent was not given
- [ ] ~~Terms of Service ~~ =>  Probably do not need this with current scope.
- [x] Privacy Policy => Required for CCPA and GDPR
- [x] ~~Contact/Imprint => For US it seems to be optional, required for EU? ~~
- [ ] #176

# Requieres Consent

- [ ] Twitch embed
- [ ] Youtube embed
- [ ] Streamable embed
- [ ] The Giving Block embed

# "Problematic" areas

- Twitch embed -> Ask for consent, link Twitch Privacy Policy
- Session/Login (OAuth) -> Ask for consent, define storage (time, place, who has access) of user data etc., provide data rights (deletion, disclosure etc.), link Privacy Policies of auth providers
- Push Service-Worker registration (makes users identifyable)
- If used: OneSignal Push Provider -> has access to browser identification + unique user id (if provided)
- Analytics? (not implemented yet) -> Ask for consent, link Privacy Policy of provider
- YT embed (not implemented yet) -> Ask for consent, link YT Privacy Policy
- Hosting (Vercel - log files?) and, if used, the CDN
- unclear: What about the Push Services by the Browsers (FCM, Mozilla, Apple etc.)
- not problematic by design: Fonts self-hosted

# Laws

## Should comply with

- GDPR (Europe)

## Probably not required

- COPPA
- CCPA/CPRA (California), VCDPA (Virigina), CPA (Colorado), UCPA (Utah), CTDPA (Connecticut)  => Probably fine to ignore, as this is neither a for-profit business nor controlled by one, https://pro.bloomberglaw.com/brief/data-privacy-laws-in-the-u-s/ https://www.mmmlaw.com/media/connecticut-becomes-the-fifth-state-to-pass-data-privacy-act/
- New York SHIELD Act "any person or business that owns or licenses private information of a New York resident"

- https://www.osano.com/articles/data-privacy-laws

**Comment by pjeweb** [comment]
@MattIPv4 How do you deal with this when merging the website (#52 ). Should we just copy the old policy? I have just a used a generator for the .gg policy and randomly choose Cookiebot (free plan). The old site had some wordpress plugin for the cookie consent if I see that correctly.

**Comment by MattIPv4** [comment]
I think for now using what we have is fine -- if/when the cutover happens, I think we should sync w/ the Alveus team and probably use their copy and check they're happy with the cookie consent that is in place.

As an aside, are we setting any tracking cookies? If we're not, we could just not have cookie consent at all?

**Comment by pjeweb** [comment]
I can only speak for the german situation. Its pretty damn stricht here. There is a new law requiring consent for any non-essential local computation on the users client [1].  Here at least the twitch embeds would need consent and I am pretty sure they does track. My dev tools are filled with local storage, cookies and indexdb entries from twitch. _We_ should not be settings tracking cookies ourselves, but that does not really matter?! One common solution in Germany is to only load the embed on an explicit click on a privacy notice.

1) https://www2.deloitte.com/dl/en/pages/legal/articles/telekommunikation-telemedien-datenschutz-gesetz.html

**Comment by MattIPv4** [comment]
Ah yes I hadn't considered that the Twitch embed probably sets a bunch of stuff. Sigh.

**Comment by MattIPv4** [comment]
@pjeweb Wanna create a dedicated issue for the admin panel stuff here, and close this out?

**Comment by pjeweb** [comment]
done for now, created a new issue for compliance tools
