### ISSUE TITLE
Notifications: Allow sending notifications from chat using command(s)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#294]
## TODO

- [x] Implement chat bot (long-running node server)
  - [x] Logged in twitch (bot) user with OAuth auth flow to allow feedback (aka send chat messages)
  - [x] Listen to chat rooms (`alveussanctuary`, `alveusgg`, …)
  - [x] Check user perms (only a list of users + channel owner)?
  - [x] Call Notification API from chat bot
  - [x] Feedback in Chat (possibly as dm)
    - [x] Require confirmation
    - [ ] ~~Allow cancelling in the first 20 seconds?~~
- [x] Implement Notification API

## Chat Commands

- `!notification [url] title ... [| message text ...]` Create a stream notification
  - `[url]` Link, optional, defaults to https://twitch.tv/alveussanctuary
- `!announcement [url] [start] [end] title ... [| message text ...]` Create an announcement
  - `[url]` Link, optional, defaults to empty (no link)
  - `[start]` Start Date/Time in the format `YYYY-MM-DD[ HH:II]`, optional, defaults to empty
  - `[end]` End Date/Time in the format `YYYY-MM-DD[ HH:II]`, only if `[start]` is present, optional, defaults to empty

### Aliases

- `!notify`
- `!announce`

### Flags

- `--no-push` to disable push
- `--no-discord` to disable discord
- `--no-site` to disable showing on website (when implemented)
- `--image=[url]` to attach an image by URL (has to be png/jpg/gif)

**Comment by MattIPv4** [comment]
> Check user perms (only a list of users + channel owner)?

Do a username lookup against the site DB and use the site-based permission?

> Feedback in Chat? -> Requires logged in twitch (bot) user with OAuth auth flow
> Require confirmation?
> Allow cancelling in the first 20 seconds?

Definitely think it should be able to report success/errors back to user -- maybe errors via DM though to avoid chat spam?

And yeah, I think a confirmation would be good to avoid accidental sends. Less sure about the need for allowing cancels though (though equally I don't mind it being implemented, and having the same for the site might be useful too)

**Comment by pjeweb** [comment]
> Definitely think it should be able to report success/errors back to user -- maybe errors via DM though to avoid chat spam?

do DMs work well on the mobile app kayla and maya use?
